### PR TITLE
Unit Tests

### PR DESCRIPTION
**Pull request by shadowtime2000**
This resolves issue #25. I have also removed unnecessary ESLint plugins such as the ESLint plugins for React and `jsx`. I saw that when errors are thrown, if the count parameter is under 0, then it throws error "Count must be greater than 0". I do not believe that fits, so I changed it to "Count must be greater than 1".

### CODE REVIEW

**Comment by shadowtime2000** [comment]
I would also recommend we connect some CI to run these unit tests on commits and pull requests. I do not understand why the unit test for `#string` does not pass, so I would suggest we let that one fail.

**Comment by shadowtime2000** [comment]
@Gridonyx Done.

**Comment by shadowtime2000** [comment]
I still don't understand why when you run the test for `#string` it doesn't throw [this](https://github.com/superhackerboy/totally-random/blob/master/dist/totallyRandom.js#L220) but throws invalid length when you it gets to [this part of the function](https://github.com/superhackerboy/totally-random/blob/master/dist/totallyRandom.js#L231).

**Comment by Gridonyx** [comment]
Hmm, yeah that does seem odd. I'm going to do some tests on my end

**Comment by Gridonyx** [comment]
Alright I think I've found the issue and am working on a fix

**Comment by Gridonyx** [comment]
Alright, the unit test should hopefully pass now after #33 gets merged

**Pull request merged**
