### PR TITLE
Random Object Key

### PR DESCRIPTION
**Pull request by shadowtime2000**
You can now get a random key from an object.

### CODE REVIEW

**Comment by superhackerboy** [comment]
What's a practical use case for this?

**Comment by shadowtime2000** [comment]
Random node from a tree.

**Comment by superhackerboy** [comment]
Do you think it would be better to return a key/pair value? Honest question :)

**Comment by shadowtime2000** [comment]
Added it.

**Comment by shadowtime2000** [comment]
Actually, I think I messed up and this is deleting some of the commits you made. I am going to close this, and I will open a new one soon with these features.

**Comment by superhackerboy** [comment]
Okay no problem!

**Pull request closed without merging**
